services:
  mongo_srv:
    image: mongo_img
    build: mongo/.
    container_name: mongo_cnt
    expose:
      - "27017"
    volumes:
      - db_vol:/data
    networks:
      app_ntw:
        ipv4_address: 172.16.6.2
    # restart: always
    # stdin_open: true
    # tty: true

  php_srv:
    image: php_img
    build: php/.
    container_name: php_cnt
    ports:
      - "9000:9000"
    volumes:
      - api_docs:/API
    networks:
      app_ntw:
        ipv4_address: 172.16.6.3
    # depends_on:
    #   - mongo_srv
    # restart: always
    # stdin_open: true
    # tty: true

volumes:
  db_vol:
    name: db_vol
    driver: local
    driver_opts:
      type: volume
      o: bind
      device: $PWD/srcs/mongo/data
  
  api_docs:
    name: api_docs
    driver: local
    driver_opts:
      type: volume
      o: bind
      device: $PWD/srcs/php/api_d

networks:
  app_ntw:
    name: app_ntw
    ipam:
      driver: default
      config:
        - subnet: "172.16.6.0/29"
  