services:
  mongo_srv:
    image: mongo_img
    build: mongoDB/.
    container_name: mongo_cnt
    expose:
      - "27017"
    # volumes:
    #   - app_vol:/APP
    networks:
      app_ntw:
        ipv4_address: 172.16.6.2
    stdin_open: true
    tty: true

  php8_srv:
    image: mphp_img
    build: php8/.
    container_name: mphp_cnt
    ports:
      - "9000:9000"
    volumes:
      - api_docs:/API
      # - app_vol:/APP
    networks:
      app_ntw:
        ipv4_address: 172.16.6.3
    stdin_open: true
    tty: true

  
volumes:
  # app_vol:
  #   name: app_vol
  #   driver: local
  #   driver_opts:
  #     type: volume
  #     o: bind
  #     device: /Users/fgradia/Desktop/wink_app
  
  api_docs:
    name: api_docs
    driver: local
    driver_opts:
      type: volume
      o: bind
      device: /Users/fgradia/Desktop/wink_app/srcs/php8/api_d

networks:
  app_ntw:
    name: app_ntw
    ipam:
      driver: default
      config:
        - subnet: "172.16.6.0/29"
  