services:
  mongo_srv:
    image: mongo_img
    build: mongo/.
    container_name: mongo_cnt
    expose:
      - "27017"
    volumes:
      - /mongo_db:/data/db:rw
    networks:
      app_ntw:
        ipv4_address: 172.16.6.2
    restart: always

  php_srv:
    image: php_img
    build: php/.
    container_name: php_cnt
    ports:
      - "9000:9000"
    volumes:
      - $PWD/srcs/php/api_d:/API:ro
    networks:
      app_ntw:
        ipv4_address: 172.16.6.3
    depends_on:
      - mongo_srv
    restart: always

networks:
  app_ntw:
    name: app_ntw
    ipam:
      driver: default
      config:
        - subnet: "172.16.6.0/29"
  